name: Release Drafter

on:
  push:
    branches:
      - develop

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        id: drafter
        # with:
        #   (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        #   config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check outputs
        run: |
          echo "Release ID - ${{ steps.drafter.outputs.id }}"
          echo "Release name - ${{ steps.drafter.outputs.name }}"
          echo "Release tag name - ${{ steps.drafter.outputs.tag_name }}"
          echo "Release body - ${{ steps.drafter.outputs.body }}"
          echo "Release html url - ${{ steps.drafter.outputs.html_url }}"
          echo "Release upload url - ${{ steps.drafter.outputs.upload_url }}"
